[project]
name = "crimsonvector"
version = "0.1.0"
description = "Benchmark utilities for RAG experiment"
readme = "README.md"
requires-python = ">=3.10,<3.13"
dependencies = [
    "datasets>=4.7.0",
    "docx2txt>=0.9",
    "elasticsearch<9",
    "langchain>=1.2.12",
    "langchain-community>=0.4.1",
    "langchain-core>=1.2.19",
    "openpyxl>=3.1.5",
    "pandas>=2.3.3",
    "pypdf>=5.9.0",
    "ragatouille>=0.0.9.post2",
    "sentence-transformers>=5.3.0",
    "sqlalchemy>=2.0.48",
    "testcontainers>=4.14.2",
    "torch>=2.10.0",
    "tqdm>=4.67.3",
    "transformers>=5.3.0",
    "voyager>=2.1.0",
    "pytrec-eval-terrier", 
]

[[tool.setuptools.packages.find]]
include = ["crimsonvector*"]
exclude = ["data*", "test*"]
