[project]
name = "raccoon"
version = "0.1.0"
description = "Benchmark utilities for RAG experiment"
readme = "README.md"
requires-python = ">=3.10,<3.13"
dependencies = []

[project.optional-dependencies]
bm25 = [
    "elasticsearch<9",
]
dataloader = [
    "docx2txt>=0.9",
    "langchain-community>=0.4.1",
    "langchain-core>=1.2.19",
    "langchain-text-splitters",
    "pypdf>=6.4.1",
    "rich",
]
dense = [
    "faiss-cpu>=1.13.2",
    "sentence-transformers>=5.3.0",
    "torch>=2.10.0",
    "rich",
]
dev = [
    "pytest",
    "ruff",
    "rich",
]
evaluation = [
    "beir",
    "datasets>=4.7.0",
    "rich",
]
gpu = [
    "cupy-cuda12x>=14.1.1",
]
linear = [
    "faiss-cpu>=1.13.2",
    "igraph>=1.0.0",
    "sentence-transformers>=5.3.0",
    "spacy>=3.8.14",
    "torch>=2.10.0",
    "rich",
]
report = [
    "psutil>=7.2.2",
    "reportlab>=4.5.1",
    "cairocffi>=1.7.1",
    "rich",
]
rerank = [
    "torch>=2.10.0",
    "transformers>=5.3.0",
    "rich",

]
sql = [
    "langchain-core>=1.2.19",
    "langchain-text-splitters",
    "sqlalchemy>=2.0.48",
    "rich",

]
synthesis = [
    "faiss-cpu>=1.13.2",
    "langchain-community>=0.4.1",
    "langchain-core>=1.2.19",
    "langchain-huggingface",
    "ollama",
    "rich",
    "sentence-transformers>=5.3.0",
    "torch>=2.10.0",
    "transformers>=5.3.0",
]
workflow = [
    "beir",
    "datasets>=4.7.0",
    "docx2txt>=0.9",
    "elasticsearch<9",
    "faiss-cpu>=1.13.2",
    "igraph>=1.0.0",
    "langchain-community>=0.4.1",
    "langchain-core>=1.2.19",
    "langchain-huggingface",
    "langchain-text-splitters",
    "ollama",
    "pandas>=2.3.3",
    "psutil>=7.2.2",
    "pypdf>=6.4.1",
    "reportlab>=4.5.1",
    "rich",
    "sentence-transformers>=5.3.0",
    "spacy>=3.8.14",
    "sqlalchemy>=2.0.48",
    "testcontainers>=4.14.2",
    "torch>=2.10.0",
    "tqdm>=4.67.3",
    "transformers>=5.3.0",
    "cairocffi>=1.7.1",
]

[[tool.setuptools.packages.find]]
include = ["raccoon*"]
exclude = ["data*", "test*"]

[tool.setuptools.package-data]
"raccoon.report" = ["images/logo.png"]

[tool.ruff]
target-version = "py310"
line-length = 120
extend-exclude = ["data", "reports"]

[tool.ruff.lint]
select = ["E9", "F821", "F822", "F823"]
